name: Build Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install pywebview google-genai pyinstaller

      - name: Run Build with Secret
        env:
          THE_KEY: ${{ secrets.THE_KEY }}
        run: |
          pyinstaller --onefile --add-data "index.html:." main.py
